//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/websvc")]
        public string Common_Sabre_Hotels_Search_OTA_HotelAvailService {
            get {
                return ((string)(this["Common_Sabre_Hotels_Search_OTA_HotelAvailService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_Reservation_OTA_HotelResService {
            get {
                return ((string)(this["Common_Sabre_Hotels_Reservation_OTA_HotelResService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_RateDetails_HotelRateDescriptionService {
            get {
                return ((string)(this["Common_Sabre_Hotels_RateDetails_HotelRateDescriptionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_PropertyDetails_HotelPropertyDescriptionService {
            get {
                return ((string)(this["Common_Sabre_Hotels_PropertyDetails_HotelPropertyDescriptionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_ModifyReservation_HotelResModifyService {
            get {
                return ((string)(this["Common_Sabre_Hotels_ModifyReservation_HotelResModifyService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_CreateSession_SessionCreateRQService {
            get {
                return ((string)(this["Common_Sabre_Hotels_CreateSession_SessionCreateRQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sws-crt.cert.sabre.com/")]
        public string Common_Sabre_Hotels_CloseSession_SessionCloseRQService {
            get {
                return ((string)(this["Common_Sabre_Hotels_CloseSession_SessionCloseRQService"]));
            }
        }
    }
}
