using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TE.Core.Tourico.Hotel.Enums
{
    public enum HotelOptionTypes
    {
        ADA_Accessible,
        AdultsOnly,
        AirportShuttle,
        BeachFront,
        Breakfast,
        BusinessCenter,
        BusinessReady,
        CarRentalCounter,
        Conventions,
        Dataport,
        Dining,
        DryClean,
        EcoCertified,
        ExecutiveFloors,
        FamilyPlan,
        FitnessCenter,
        FreeLocalCalls,
        FreeParking,
        FreeShuttle,
        FreeWifiInMeetingRooms,
        FreeWifiInPublicSpaces,
        FreeWifiInRooms,
        FullServiceSpa,
        GameFacilities,
        Golf,
        GovtSafetyFire,
        HighSpeedInternet,
        HypoallergenicRooms,
        IndoorPool,
        IndPetRestriction,
        InRoomCoffeeTea,
        InRoomMiniBar,
        InRoomRefrigerator,
        InRoomSafe,
        InteriorDoorways,
        Jacuzzi,
        KidsFacilities,
        KitchenFacilities,
        MealService,
        MeetingFacilities,
        NoAdultTV,
        NonSmoking,
        OutdoorPool,
        Parking,
        Pets,
        Pool,
        PublicTransportationAdjacent,
        Recreation,
        RestrictedRoomAccess,
        RoomService,
        RoomService24Hours,
        RoomsWithBalcony,
        SkiInOutProperty,
        SmokeFree,
        SmokingRoomsAvail,
        Tennis,
        WaterPurificationSystem,
        Wheelchair
    }
}
