//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.hotelDestSvc {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class CustomExpMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorNumberField;
        
        private bool errorNumberFieldSpecified;
        
        private string stackTraceField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorNumberSpecified {
            get {
                return this.errorNumberFieldSpecified;
            }
            set {
                this.errorNumberFieldSpecified = value;
                this.RaisePropertyChanged("ErrorNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Activity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activityIdField;
        
        private string activityNameField;
        
        private int destinationIdField;
        
        private string activityLatitudeField;
        
        private string activityLongitudeField;
        
        private string addressField;
        
        private string zipField;
        
        private string cityField;
        
        private string locationField;
        
        private string stateField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        private string destinationCodeField;
        
        private double starsField;
        
        private string statusField;
        
        private byte bestValField;
        
        private string activityCategoryIDField;
        
        private string activityCategoryField;
        
        private int providerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int activityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
                this.RaisePropertyChanged("activityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activityName {
            get {
                return this.activityNameField;
            }
            set {
                this.activityNameField = value;
                this.RaisePropertyChanged("activityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int destinationId {
            get {
                return this.destinationIdField;
            }
            set {
                this.destinationIdField = value;
                this.RaisePropertyChanged("destinationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activityLatitude {
            get {
                return this.activityLatitudeField;
            }
            set {
                this.activityLatitudeField = value;
                this.RaisePropertyChanged("activityLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activityLongitude {
            get {
                return this.activityLongitudeField;
            }
            set {
                this.activityLongitudeField = value;
                this.RaisePropertyChanged("activityLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationCode {
            get {
                return this.destinationCodeField;
            }
            set {
                this.destinationCodeField = value;
                this.RaisePropertyChanged("destinationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
                this.RaisePropertyChanged("stars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte bestVal {
            get {
                return this.bestValField;
            }
            set {
                this.bestValField = value;
                this.RaisePropertyChanged("bestVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activityCategoryID {
            get {
                return this.activityCategoryIDField;
            }
            set {
                this.activityCategoryIDField = value;
                this.RaisePropertyChanged("activityCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activityCategory {
            get {
                return this.activityCategoryField;
            }
            set {
                this.activityCategoryField = value;
                this.RaisePropertyChanged("activityCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int providerId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
                this.RaisePropertyChanged("providerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Hotel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hotelIdField;
        
        private string hotelNameField;
        
        private int destinationIdField;
        
        private string hotelLatitudeField;
        
        private string hotelLongitudeField;
        
        private string addressField;
        
        private string zipField;
        
        private string cityField;
        
        private string locationField;
        
        private string stateField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        private string destinationCodeField;
        
        private double starsField;
        
        private string statusField;
        
        private byte bestValField;
        
        private int providerIdField;
        
        private bool uploadedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int hotelId {
            get {
                return this.hotelIdField;
            }
            set {
                this.hotelIdField = value;
                this.RaisePropertyChanged("hotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
                this.RaisePropertyChanged("hotelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int destinationId {
            get {
                return this.destinationIdField;
            }
            set {
                this.destinationIdField = value;
                this.RaisePropertyChanged("destinationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotelLatitude {
            get {
                return this.hotelLatitudeField;
            }
            set {
                this.hotelLatitudeField = value;
                this.RaisePropertyChanged("hotelLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hotelLongitude {
            get {
                return this.hotelLongitudeField;
            }
            set {
                this.hotelLongitudeField = value;
                this.RaisePropertyChanged("hotelLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationCode {
            get {
                return this.destinationCodeField;
            }
            set {
                this.destinationCodeField = value;
                this.RaisePropertyChanged("destinationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
                this.RaisePropertyChanged("stars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte bestVal {
            get {
                return this.bestValField;
            }
            set {
                this.bestValField = value;
                this.RaisePropertyChanged("bestVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int providerId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
                this.RaisePropertyChanged("providerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool uploaded {
            get {
                return this.uploadedField;
            }
            set {
                this.uploadedField = value;
                this.RaisePropertyChanged("uploaded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(City))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(State))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Country))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Continent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class BaseNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int elementTypeField;
        
        private int destinationIdField;
        
        private string providerField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int elementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
                this.RaisePropertyChanged("elementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int destinationId {
            get {
                return this.destinationIdField;
            }
            set {
                this.destinationIdField = value;
                this.RaisePropertyChanged("destinationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("provider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class CityLocation : BaseNode {
        
        private Hotel[] hotelsField;
        
        private Activity[] activitiesField;
        
        private string locationField;
        
        private string destinationCodeField;
        
        private string cityField;
        
        private int cityDestinationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Hotel[] Hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
                this.RaisePropertyChanged("Hotels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Activity[] Activities {
            get {
                return this.activitiesField;
            }
            set {
                this.activitiesField = value;
                this.RaisePropertyChanged("Activities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationCode {
            get {
                return this.destinationCodeField;
            }
            set {
                this.destinationCodeField = value;
                this.RaisePropertyChanged("destinationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int cityDestinationId {
            get {
                return this.cityDestinationIdField;
            }
            set {
                this.cityDestinationIdField = value;
                this.RaisePropertyChanged("cityDestinationId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class City : BaseNode {
        
        private CityLocation[] cityLocationField;
        
        private Hotel[] hotelsField;
        
        private Activity[] activitiesField;
        
        private string destinationCodeField;
        
        private string cityLatitudeField;
        
        private string cityLongitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CityLocation", Order=0)]
        public CityLocation[] CityLocation {
            get {
                return this.cityLocationField;
            }
            set {
                this.cityLocationField = value;
                this.RaisePropertyChanged("CityLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Hotel[] Hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
                this.RaisePropertyChanged("Hotels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Activity[] Activities {
            get {
                return this.activitiesField;
            }
            set {
                this.activitiesField = value;
                this.RaisePropertyChanged("Activities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationCode {
            get {
                return this.destinationCodeField;
            }
            set {
                this.destinationCodeField = value;
                this.RaisePropertyChanged("destinationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cityLatitude {
            get {
                return this.cityLatitudeField;
            }
            set {
                this.cityLatitudeField = value;
                this.RaisePropertyChanged("cityLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cityLongitude {
            get {
                return this.cityLongitudeField;
            }
            set {
                this.cityLongitudeField = value;
                this.RaisePropertyChanged("cityLongitude");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class State : BaseNode {
        
        private City[] cityField;
        
        private string stateShortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("City", Order=0)]
        public City[] City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateShort {
            get {
                return this.stateShortField;
            }
            set {
                this.stateShortField = value;
                this.RaisePropertyChanged("StateShort");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Country : BaseNode {
        
        private State[] stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("State", Order=0)]
        public State[] State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Continent : BaseNode {
        
        private Country[] countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Country", Order=0)]
        public Country[] Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class DestinationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Continent[] continentField;
        
        private string versionField;
        
        private string cultureField;
        
        private int resultNumField;
        
        private string serverTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Continent", Order=0)]
        public Continent[] Continent {
            get {
                return this.continentField;
            }
            set {
                this.continentField = value;
                this.RaisePropertyChanged("Continent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ResultNum {
            get {
                return this.resultNumField;
            }
            set {
                this.resultNumField = value;
                this.RaisePropertyChanged("ResultNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServerTime {
            get {
                return this.serverTimeField;
            }
            set {
                this.serverTimeField = value;
                this.RaisePropertyChanged("ServerTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Provider : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class Destination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string continentField;
        
        private string countryField;
        
        private string stateField;
        
        private string cityField;
        
        private Provider[] providersField;
        
        private System.DateTime statusDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Continent {
            get {
                return this.continentField;
            }
            set {
                this.continentField = value;
                this.RaisePropertyChanged("Continent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ProviderType", IsNullable=false)]
        public Provider[] Providers {
            get {
                return this.providersField;
            }
            set {
                this.providersField = value;
                this.RaisePropertyChanged("Providers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime StatusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
                this.RaisePropertyChanged("StatusDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/Contracts", ConfigurationName="hotelDestSvc.IDestinationContracts")]
    public interface IDestinationContracts {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://touricoholidays.com/WSDestinations/2008/08/DataContracts) of message DestinationRequest does not match the default value (http://touricoholidays.com/WSDestinations/2008/08/Contracts)
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetDestinationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Common.hotelDestSvc.CustomExpMsg), Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetDestinationCustomExceptionMessageFault", Name="CustomExpMsg", Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseNode))]
        Common.hotelDestSvc.DestinationResultContainer GetDestination(Common.hotelDestSvc.DestinationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetDestinationResponse")]
        System.Threading.Tasks.Task<Common.hotelDestSvc.DestinationResultContainer> GetDestinationAsync(Common.hotelDestSvc.DestinationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://touricoholidays.com/WSDestinations/2008/08/DataContracts) of message HotelDestinationRequest does not match the default value (http://touricoholidays.com/WSDestinations/2008/08/Contracts)
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetHotelsByDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetHotelsByDestinationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Common.hotelDestSvc.CustomExpMsg), Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetHotelsByDestinationCustomExceptionMessageFault", Name="CustomExpMsg", Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseNode))]
        Common.hotelDestSvc.HotelDestinationResultContainer GetHotelsByDestination(Common.hotelDestSvc.HotelDestinationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetHotelsByDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetHotelsByDestinationResponse")]
        System.Threading.Tasks.Task<Common.hotelDestSvc.HotelDestinationResultContainer> GetHotelsByDestinationAsync(Common.hotelDestSvc.HotelDestinationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://touricoholidays.com/WSDestinations/2008/08/DataContracts) of message ActivityDestinationRequest does not match the default value (http://touricoholidays.com/WSDestinations/2008/08/Contracts)
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetActivitiesByDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetActivitiesByDestinationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Common.hotelDestSvc.CustomExpMsg), Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetActivitiesByDestinationCustomExceptionMessageFault", Name="CustomExpMsg", Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseNode))]
        Common.hotelDestSvc.ActivityDestinationResultContainer GetActivitiesByDestination(Common.hotelDestSvc.ActivityDestinationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetActivitiesByDestination", ReplyAction="http://touricoholidays.com/WSDestinations/2008/08/Contracts/IDestinationContracts" +
            "/GetActivitiesByDestinationResponse")]
        System.Threading.Tasks.Task<Common.hotelDestSvc.ActivityDestinationResultContainer> GetActivitiesByDestinationAsync(Common.hotelDestSvc.ActivityDestinationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public partial class LoginHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private Culture cultureField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Culture culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
    public enum Culture {
        
        /// <remarks/>
        en_US,
        
        /// <remarks/>
        he_IL,
        
        /// <remarks/>
        es_ES,
        
        /// <remarks/>
        pt_PT,
        
        /// <remarks/>
        ru_RU,
        
        /// <remarks/>
        fr_FR,
        
        /// <remarks/>
        de_DE,
        
        /// <remarks/>
        ja_JP,
        
        /// <remarks/>
        it_IT,
        
        /// <remarks/>
        zh_CN,
        
        /// <remarks/>
        ko_KR,
        
        /// <remarks/>
        pl_PL,
        
        /// <remarks/>
        zh_TW,
        
        /// <remarks/>
        nl_NL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDestination", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class DestinationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        public Common.hotelDestSvc.LoginHeader LoginHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.Destination Destination;
        
        public DestinationRequest() {
        }
        
        public DestinationRequest(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            this.LoginHeader = LoginHeader;
            this.Destination = Destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DestinationResponse", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class DestinationResultContainer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.DestinationResult DestinationResult;
        
        public DestinationResultContainer() {
        }
        
        public DestinationResultContainer(Common.hotelDestSvc.DestinationResult DestinationResult) {
            this.DestinationResult = DestinationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotelsByDestination", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class HotelDestinationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        public Common.hotelDestSvc.LoginHeader LoginHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.Destination Destination;
        
        public HotelDestinationRequest() {
        }
        
        public HotelDestinationRequest(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            this.LoginHeader = LoginHeader;
            this.Destination = Destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HotelsByDestinationResponse", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class HotelDestinationResultContainer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.DestinationResult DestinationResult;
        
        public HotelDestinationResultContainer() {
        }
        
        public HotelDestinationResultContainer(Common.hotelDestSvc.DestinationResult DestinationResult) {
            this.DestinationResult = DestinationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActivitiesByDestination", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class ActivityDestinationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts")]
        public Common.hotelDestSvc.LoginHeader LoginHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.Destination Destination;
        
        public ActivityDestinationRequest() {
        }
        
        public ActivityDestinationRequest(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            this.LoginHeader = LoginHeader;
            this.Destination = Destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivitiesByDestinationResponse", WrapperNamespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", IsWrapped=true)]
    public partial class ActivityDestinationResultContainer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://touricoholidays.com/WSDestinations/2008/08/DataContracts", Order=0)]
        public Common.hotelDestSvc.DestinationResult DestinationResult;
        
        public ActivityDestinationResultContainer() {
        }
        
        public ActivityDestinationResultContainer(Common.hotelDestSvc.DestinationResult DestinationResult) {
            this.DestinationResult = DestinationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDestinationContractsChannel : Common.hotelDestSvc.IDestinationContracts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DestinationContractsClient : System.ServiceModel.ClientBase<Common.hotelDestSvc.IDestinationContracts>, Common.hotelDestSvc.IDestinationContracts {
        
        public DestinationContractsClient() {
        }
        
        public DestinationContractsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DestinationContractsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DestinationContractsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DestinationContractsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.hotelDestSvc.DestinationResultContainer Common.hotelDestSvc.IDestinationContracts.GetDestination(Common.hotelDestSvc.DestinationRequest request) {
            return base.Channel.GetDestination(request);
        }
        
        public Common.hotelDestSvc.DestinationResult GetDestination(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.DestinationRequest inValue = new Common.hotelDestSvc.DestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            Common.hotelDestSvc.DestinationResultContainer retVal = ((Common.hotelDestSvc.IDestinationContracts)(this)).GetDestination(inValue);
            return retVal.DestinationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Common.hotelDestSvc.DestinationResultContainer> Common.hotelDestSvc.IDestinationContracts.GetDestinationAsync(Common.hotelDestSvc.DestinationRequest request) {
            return base.Channel.GetDestinationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Common.hotelDestSvc.DestinationResultContainer> GetDestinationAsync(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.DestinationRequest inValue = new Common.hotelDestSvc.DestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            return ((Common.hotelDestSvc.IDestinationContracts)(this)).GetDestinationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.hotelDestSvc.HotelDestinationResultContainer Common.hotelDestSvc.IDestinationContracts.GetHotelsByDestination(Common.hotelDestSvc.HotelDestinationRequest request) {
            return base.Channel.GetHotelsByDestination(request);
        }
        
        public Common.hotelDestSvc.DestinationResult GetHotelsByDestination(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.HotelDestinationRequest inValue = new Common.hotelDestSvc.HotelDestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            Common.hotelDestSvc.HotelDestinationResultContainer retVal = ((Common.hotelDestSvc.IDestinationContracts)(this)).GetHotelsByDestination(inValue);
            return retVal.DestinationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Common.hotelDestSvc.HotelDestinationResultContainer> Common.hotelDestSvc.IDestinationContracts.GetHotelsByDestinationAsync(Common.hotelDestSvc.HotelDestinationRequest request) {
            return base.Channel.GetHotelsByDestinationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Common.hotelDestSvc.HotelDestinationResultContainer> GetHotelsByDestinationAsync(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.HotelDestinationRequest inValue = new Common.hotelDestSvc.HotelDestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            return ((Common.hotelDestSvc.IDestinationContracts)(this)).GetHotelsByDestinationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.hotelDestSvc.ActivityDestinationResultContainer Common.hotelDestSvc.IDestinationContracts.GetActivitiesByDestination(Common.hotelDestSvc.ActivityDestinationRequest request) {
            return base.Channel.GetActivitiesByDestination(request);
        }
        
        public Common.hotelDestSvc.DestinationResult GetActivitiesByDestination(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.ActivityDestinationRequest inValue = new Common.hotelDestSvc.ActivityDestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            Common.hotelDestSvc.ActivityDestinationResultContainer retVal = ((Common.hotelDestSvc.IDestinationContracts)(this)).GetActivitiesByDestination(inValue);
            return retVal.DestinationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Common.hotelDestSvc.ActivityDestinationResultContainer> Common.hotelDestSvc.IDestinationContracts.GetActivitiesByDestinationAsync(Common.hotelDestSvc.ActivityDestinationRequest request) {
            return base.Channel.GetActivitiesByDestinationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Common.hotelDestSvc.ActivityDestinationResultContainer> GetActivitiesByDestinationAsync(Common.hotelDestSvc.LoginHeader LoginHeader, Common.hotelDestSvc.Destination Destination) {
            Common.hotelDestSvc.ActivityDestinationRequest inValue = new Common.hotelDestSvc.ActivityDestinationRequest();
            inValue.LoginHeader = LoginHeader;
            inValue.Destination = Destination;
            return ((Common.hotelDestSvc.IDestinationContracts)(this)).GetActivitiesByDestinationAsync(inValue);
        }
    }
}
